// scripts/build-tokens.ts
// ─────────────────────────────────────────────────────────────────────────────
// Generates app/styles/tokens.generated.css from design/tokens.ts.
//
// Wire it up in package.json:
//   "scripts": {
//     "tokens":   "tsx scripts/build-tokens.ts",
//     "prebuild": "npm run tokens",
//     "predev":   "npm run tokens"
//   }
// Commit the generated file so diffs are reviewable; CI can run `npm run tokens`
// and fail if git is dirty (drift guard).
//
// app/styles/colors_and_type.css then becomes:
//   @import "./tokens.generated.css";   ← the :root block, now generated
//   …the EXISTING raw-element styling (h1–h6, body, a, .eyebrow, .ledger …)
// Only the :root color/scale block moves out; element styling stays, so the
// deck looks byte-for-byte identical.
// ─────────────────────────────────────────────────────────────────────────────
import { writeFileSync } from 'node:fs';
import {
  primitives, font, fontSize, radius, shadow, themes, type SemanticMap,
} from '../design/tokens';

const block = (obj: Record<string, string>) =>
  Object.entries(obj).map(([k, v]) => `  ${k}: ${v};`).join('\n');

const semanticBlock = (map: SemanticMap) =>
  Object.entries(map).map(([role, ref]) => `  ${role}: var(${ref});`).join('\n');

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand.
   Source: design/tokens.ts. Run \`npm run tokens\` to regenerate. */

:root {
  /* Primitives */
${block(primitives)}

  /* Type */
${block(font)}
${block(fontSize)}

  /* Radius / shadow */
${block(radius)}
${block(shadow)}
}

/* Semantic roles: LIGHT (default) */
:root,
[data-theme="light"] {
${semanticBlock(themes.light)}
}

/* Semantic roles: INVERSE (dark navy fields) */
[data-theme="inverse"] {
${semanticBlock(themes.inverse)}
}
`;

writeFileSync(new URL('../app/styles/tokens.generated.css', import.meta.url), css);
console.log('✓ wrote app/styles/tokens.generated.css');
