// scripts/build-tokens.ts
// ─────────────────────────────────────────────────────────────────────────────
// Generates app/styles/tokens.generated.css from design/tokens.ts.
//
// Wired into package.json:
//   "scripts": {
//     "tokens":   "tsx scripts/build-tokens.ts",
//     "prebuild": "npm run tokens",
//     "predev":   "npm run tokens"
//   }
// The generated file IS committed so diffs are reviewable; CI can run
// `npm run tokens` and fail if git is dirty (drift guard).
//
// app/styles/colors_and_type.css then becomes:
//   @import "./tokens.generated.css";   ← the :root block, now generated
//   …the EXISTING raw-element styling (h1–h6, body, a, .eyebrow, .ledger …)
// Only the :root block moves out; element styling stays, so the deck looks
// byte-for-byte identical.
//
// For every primitive we ALSO emit an `--x-rgb` channel companion
// (e.g. `--navy-rgb: 11 37 69;`). Tailwind colors are `rgb(var(--x-rgb) /
// <alpha-value>)`, which keeps opacity modifiers (bg-brass/15, text-paper/60,
// ring-brass/40, bg-navy-deep/50, …) working — a plain `var(--navy)` would
// silently drop the alpha and change the render.
// ─────────────────────────────────────────────────────────────────────────────
import { writeFileSync } from 'node:fs';
import {
  primitives, derived, legacyRoles, font, fontSize, lineHeight, tracking,
  radius, space, borderWeight, shadow, motion, layout, themes,
  type SemanticMap,
} from '../design/tokens';

/** "#0B2545" → "11 37 69" (space-separated channels for rgb(... / <alpha>)). */
function hexToChannels(hex: string): string {
  const h = hex.replace('#', '');
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

const block = (obj: Record<string, string>) =>
  Object.entries(obj).map(([k, v]) => `  ${k}: ${v};`).join('\n');

/** Primitives + their channel companions. */
const primitiveBlock = Object.entries(primitives)
  .map(([k, v]) => `  ${k}: ${v};\n  ${k}-rgb: ${hexToChannels(v)};`)
  .join('\n');

/** Semantic roles: color ref + channel ref, so utilities support opacity. */
const semanticBlock = (map: SemanticMap) =>
  Object.entries(map)
    .map(([role, ref]) => `  ${role}: var(${ref});\n  ${role}-rgb: var(${ref}-rgb);`)
    .join('\n');

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand.
   Source: design/tokens.ts. Run \`npm run tokens\` to regenerate. */

:root {
  /* ── Primitives (full color + rgb channels) ── */
${primitiveBlock}

  /* ── Derived tints ── */
${block(derived)}

  /* ── Legacy semantic role aliases ── */
${block(legacyRoles)}

  /* ── Type: families ── */
${block(font)}

  /* ── Type: size scale ── */
${block(fontSize)}

  /* ── Type: line height ── */
${block(lineHeight)}

  /* ── Type: tracking ── */
${block(tracking)}

  /* ── Radius ── */
${block(radius)}

  /* ── Spacing (8px grid) ── */
${block(space)}

  /* ── Border weights ── */
${block(borderWeight)}

  /* ── Shadows ── */
${block(shadow)}

  /* ── Motion ── */
${block(motion)}

  /* ── Layout rhythm ── */
${block(layout)}
}

/* ── TIER 2 semantic roles: LIGHT (default) ── */
:root,
[data-theme="light"] {
${semanticBlock(themes.light)}
}

/* ── TIER 2 semantic roles: INVERSE (dark navy fields) ── */
[data-theme="inverse"] {
${semanticBlock(themes.inverse)}
}
`;

writeFileSync(new URL('../app/styles/tokens.generated.css', import.meta.url), css);
console.log('✓ wrote app/styles/tokens.generated.css');
